### ISSUE TITLE
Table ids

### ISSUE THREAD

**Issue by Marhabibi** [bfetahu/wiki_tables#1]
Table ids in the ground truth ("Source Table ID" or "Matching Table ID") do not match with the ones ('id' = TBL_ID field) in the table data. For example in table data for article "Renae_Geerlings", section "Filmography", there is only one table with id "2451", but in the ground truth, there is the following line:

Travis Wester	Renae Geerlings	Film	Filmography	7231	3183	equivalent

Second document, second section and second id do not match with the ones in the table data. 

Would you please correct me, if I am wrong?

**Comment by bfetahu** [comment]
You are right. There has been some table ID updates which seems that were not updated as well where I have shared the data. 

Please check again now. I have updated the raw data and the ground-truth, in [1] and [2], respectively.

[1] http://l3s.de/~fetahu/wiki_tables/data/table_data/html_data/structured_html_table_data.json.gz

[2] http://l3s.de/~fetahu/wiki_tables/data/gt_data/table_pair_evaluation_eq_sub_irrel_labels.tsv
